 with VENDOR as (
    select * from {{ref('raw2_netsuite_vendors') }}
), 

renamed as ( 
select
ID as vendor_id,
ACCOUNTNUMBER,
ALTNAME,
BALANCE,
CATEGORY,
COMMENTS,
COMPANYNAME,
CREDITLIMIT,
CURRENCY,
CUSTENTITY_SW_AWA_BILL_APPROVER1,
DEFAULTBILLINGADDRESS,
DEFAULTSHIPPINGADDRESS,
EMAIL,
ENTITYID,
ENTITYNUMBER,
ENTITYTITLE,
EXTERNALID,
FIRSTNAME,
LASTMODIFIEDDATE,
LASTNAME,
LEGALNAME,
FIRSTNAME || ' ' || LASTNAME as FULL_NAME,
PHONE,
PURCHASEORDERAMOUNT,
PURCHASEORDERQUANTITY,
PURCHASEORDERQUANTITYDIFF,
RECEIPTAMOUNT,
RECEIPTQUANTITY,
RECEIPTQUANTITYDIFF,
UNBILLEDORDERS,
UNBILLEDORDERSPRIMARY,
URL,
_FIVETRAN_DELETED,
_FIVETRAN_SYNCED

from VENDOR
where _FIVETRAN_DELETED = 'FALSE'
)
select * from renamed


